# Generated by Django 4.0.6 on 2022-07-06 19:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('Stats', 'Stats'), ('Mechine Learning', 'Mechine Learning'), ('Deep Learning', 'Deep Learning'), ('NLP', 'NLP')], max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
