# Generated by Django 4.0.6 on 2022-07-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_blog_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesslider',
            name='icon',
            field=models.CharField(default='fa fa-cogs', max_length=100),
        ),
    ]
