# Generated by Django 4.0.6 on 2022-07-07 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_servicesslider_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='awards_received',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='completed_projects',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='happy_clients',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='inprogress_projects',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='achievements',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievements',
            name='icon',
            field=models.CharField(default='fa fa-cogs', max_length=100),
        ),
        migrations.AddField(
            model_name='achievements',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
