# Generated by Django 4.0.6 on 2022-07-07 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_achievements_awards_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievements',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
