# Generated by Django 4.0.6 on 2022-07-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_repositary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repositary',
            old_name='url',
            new_name='git_url',
        ),
    ]
