# Generated by Django 4.0.6 on 2022-07-07 07:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_url_repositary_git_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('snippet', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, upload_to='media/blogimages/')),
                ('category', models.CharField(choices=[('Python', 'Python'), ('Stats', 'Stats'), ('Mechine Learning', 'Mechine Learning'), ('Deep Learning', 'Deep Learning'), ('NLP', 'NLP')], max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('time_to_read', models.CharField(max_length=255)),
                ('git_url', models.CharField(max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='repositary',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
