# Generated by Django 4.0.6 on 2022-07-07 09:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_project_alter_repositary_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('description1', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('description2', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('resume_url', models.URLField(verbose_name='Resume URL')),
                ('image1', models.ImageField(upload_to='media/profile/', verbose_name='Image')),
                ('image2', models.ImageField(upload_to='media/profile/', verbose_name='Image')),
                ('video_url', models.URLField(verbose_name='Video URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
