# Generated by Django 4.0.6 on 2022-07-07 09:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_homepageprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageprofile',
            name='description3',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
