# Generated by Django 4.0.6 on 2022-07-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_homepageprofile_description3'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='blog-title', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('Stats', 'Stats'), ('Machine Learning', 'Machine Learning'), ('Deep Learning', 'Deep Learning'), ('NLP', 'NLP')], max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('Stats', 'Stats'), ('Machine Learning', 'Machine Learning'), ('Deep Learning', 'Deep Learning'), ('NLP', 'NLP')], max_length=255),
        ),
    ]
