# Generated by Django 4.0.6 on 2022-07-10 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_blog_slug_alter_blog_category_alter_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
