# Generated by Django 4.0.6 on 2022-07-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
