# Generated by Django 4.0.6 on 2022-07-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_mailmessage_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='url_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='users',
            field=models.ManyToManyField(to='core.subscribers'),
        ),
    ]
