# Generated by Django 4.0.6 on 2022-07-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_mailmessage_url_link_mailmessage_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='send_it',
            field=models.BooleanField(default=False),
        ),
    ]
