# Generated by Django 4.0.6 on 2022-07-14 07:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_mailmessage_send_it'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailmessage',
            options={'verbose_name': 'Emails to send', 'verbose_name_plural': 'Emails to send'},
        ),
        migrations.RemoveField(
            model_name='mailmessage',
            name='url_link',
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='message',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
