# Generated by Django 4.0.6 on 2022-07-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_mailmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmessage',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
