# Generated by Django 4.0.6 on 2022-07-14 07:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_mailmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmessage',
            name='message',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
