# Generated by Django 4.0.6 on 2022-07-14 08:32

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_mailmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageprofile',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Video URL'),
        ),
    ]
