# Generated by Django 4.0.6 on 2022-07-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_aboutpersonalawards_aboutprofile_aboutservices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutprofile',
            name='position',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
