# Generated by Django 4.0.6 on 2022-07-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_aboutprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutskills',
            name='percent',
            field=models.IntegerField(max_length=255),
        ),
    ]
