# Generated by Django 4.0.6 on 2022-07-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_aboutskills_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutskills',
            name='percent',
            field=models.IntegerField(),
        ),
    ]
