# Generated by Django 4.0.6 on 2022-07-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_aboutskills_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='url',
            new_name='socialmediaurl',
        ),
    ]
