# Generated by Django 4.0.6 on 2022-07-14 14:56

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_rename_url_socialmedia_socialmediaurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutprofile',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='homepageprofile',
            name='image1',
            field=models.ImageField(blank=True, default='', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='homepageprofile',
            name='image2',
            field=models.ImageField(blank=True, default='', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='homepageprofile',
            name='video_url',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/', validators=[cloudinary_storage.validators.validate_video]),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_image',
            field=models.ImageField(blank=True, default='', upload_to='profiles/'),
        ),
    ]
