# Generated by Django 4.0.6 on 2022-07-14 15:14

import ckeditor.fields
from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_aboutprofile_image_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageprofile',
            name='description4',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='homepageprofile',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Video URL'),
        ),
    ]
